Models/Kendaraan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RentalKendaraan_116.Models
{
    public partial class Kendaraan
    {
        public Kendaraan()
        {
            Peminjaman = new HashSet<Peminjaman>();
        }

        public int IdKendaraan { get; set; }
        [Required(ErrorMessage = "Nama Kendaraan Tidak boleh kosong")]
        public string NamaKendaraan { get; set; }
        [Required(ErrorMessage = "No Polisi Tidak boleh kosong")]
        public string NoPolisi { get; set; }
        [Required(ErrorMessage = "No STNK Tidak boleh kosong")]
        [MinLength(8, ErrorMessage = "No Hp Minimal 8 angka")]
        [MaxLength(8, ErrorMessage = "No Hp Minimal 8 angka")]
        public string NoStnk { get; set; }
        public int? IdJenisKendaraan { get; set; }
        public string Ketersediaan { get; set; }

        public JenisKendaraan IdJenisKendaraanNavigation { get; set; }
        public ICollection<Peminjaman> Peminjaman { get; set; }
    }
}

Controllers/KendaraansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RentalKendaraan_116.Models;

namespace RentalKendaraan_116.Controllers
{
    public class KendaraansController : Controller
    {
        private readonly RentalKendaraanContext _context;

        public KendaraansController(RentalKendaraanContext context)
        {
            _context = context;
        }

        // GET: Kendaraans
        public async Task<IActionResult> Index(string ktsd, string searchString, string sortOrder, string currentFilter, int? pageNumber)
        {
            //buat list menyimpan ketersediaan
            var ktsdList = new List<string>();

            //query mengambil data
            var ktsdQuery = from d in _context.Kendaraan orderby d.Ketersediaan select d.Ketersediaan;

            ktsdList.AddRange(ktsdQuery.Distinct());

            //untuk menampilkan di view
            ViewBag.ktsd = new SelectList(ktsdList);

            //panggil db context
            var menu = from m in _context.Kendaraan.Include(k => k.IdJenisKendaraanNavigation) select m;

            //untuk memilih dwopdownlist ketersediaan
            if (!string.IsNullOrEmpty(ktsd))
            {
                menu = menu.Where(x => x.Ketersediaan == ktsd);

            }
            //untuk search data
            if (!string.IsNullOrEmpty(searchString))
            {
                menu = menu.Where(s => s.NoPolisi.Contains(searchString) || s.NamaKendaraan.Contains(searchString)
                || s.NoStnk.Contains(searchString));
            }

            //untuk sorting
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            switch (sortOrder)
            {
                case "name_desc":
                    menu = menu.OrderByDescending(s => s.NamaKendaraan);
                    break;
                case "Date":
                    menu = menu.OrderBy(s => s.Ketersediaan);
                    break;
                case "date_desc":
                    menu = menu.OrderByDescending(s => s.Ketersediaan);
                    break;
                default:
                    menu = menu.OrderBy(s => s.NamaKendaraan);
                    break;
            }

            //membuat pagedList
            ViewData["CurrentSort"] = sortOrder;
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            //definisi jumlah data pada halaman
            int pageSize = 5;

            return View(await PaginatedList<Kendaraan>.CreateAsync(menu.AsNoTracking(), pageNumber ?? 1, pageSize));


            //var rentalKendaraanContext = _context.Kendaraan.Include(k => k.IdJenisKendaraanNavigation);
            //return View(await rentalKendaraanContext.ToListAsync());
        }

        // GET: Kendaraans/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kendaraan = await _context.Kendaraan
                .Include(k => k.IdJenisKendaraanNavigation)
                .FirstOrDefaultAsync(m => m.IdKendaraan == id);
            if (kendaraan == null)
            {
                return NotFound();
            }

            return View(kendaraan);
        }

        // GET: Kendaraans/Create
        public IActionResult Create()
        {
            ViewData["IdJenisKendaraan"] = new SelectList(_context.JenisKendaraan, "IdJenisKendaraan", "IdJenisKendaraan");
            return View();
        }

        // POST: Kendaraans/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdKendaraan,NamaKendaraan,NoPolisi,NoStnk,IdJenisKendaraan,Ketersediaan")] Kendaraan kendaraan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kendaraan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdJenisKendaraan"] = new SelectList(_context.JenisKendaraan, "IdJenisKendaraan", "IdJenisKendaraan", kendaraan.IdJenisKendaraan);
            return View(kendaraan);
        }

        // GET: Kendaraans/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kendaraan = await _context.Kendaraan.FindAsync(id);
            if (kendaraan == null)
            {
                return NotFound();
            }
            ViewData["IdJenisKendaraan"] = new SelectList(_context.JenisKendaraan, "IdJenisKendaraan", "IdJenisKendaraan", kendaraan.IdJenisKendaraan);
            return View(kendaraan);
        }

        // POST: Kendaraans/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdKendaraan,NamaKendaraan,NoPolisi,NoStnk,IdJenisKendaraan,Ketersediaan")] Kendaraan kendaraan)
        {
            if (id != kendaraan.IdKendaraan)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kendaraan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KendaraanExists(kendaraan.IdKendaraan))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdJenisKendaraan"] = new SelectList(_context.JenisKendaraan, "IdJenisKendaraan", "IdJenisKendaraan", kendaraan.IdJenisKendaraan);
            return View(kendaraan);
        }

        // GET: Kendaraans/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kendaraan = await _context.Kendaraan
                .Include(k => k.IdJenisKendaraanNavigation)
                .FirstOrDefaultAsync(m => m.IdKendaraan == id);
            if (kendaraan == null)
            {
                return NotFound();
            }

            return View(kendaraan);
        }

        // POST: Kendaraans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var kendaraan = await _context.Kendaraan.FindAsync(id);
            _context.Kendaraan.Remove(kendaraan);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KendaraanExists(int id)
        {
            return _context.Kendaraan.Any(e => e.IdKendaraan == id);
        }
    }
}

Views/Kendaraans/Create.cshtml
@model RentalKendaraan_116.Models.Kendaraan

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Kendaraan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdKendaraan" class="control-label"></label>
                <input asp-for="IdKendaraan" class="form-control" />
                <span asp-validation-for="IdKendaraan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NamaKendaraan" class="control-label"></label>
                <input asp-for="NamaKendaraan" class="form-control" />
                <span asp-validation-for="NamaKendaraan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoPolisi" class="control-label"></label>
                <input asp-for="NoPolisi" class="form-control" />
                <span asp-validation-for="NoPolisi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoStnk" class="control-label"></label>
                <input asp-for="NoStnk" class="form-control" />
                <span asp-validation-for="NoStnk" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdJenisKendaraan" class="control-label"></label>
                <select asp-for="IdJenisKendaraan" class ="form-control" asp-items="ViewBag.IdJenisKendaraan"></select>
            </div>
            <div class="form-group">
                <label asp-for="Ketersediaan" class="control-label"></label>
                <input asp-for="Ketersediaan" class="form-control" />
                <span asp-validation-for="Ketersediaan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Kendaraans/Delete.cshtml
@model RentalKendaraan_116.Models.Kendaraan

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Kendaraan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NamaKendaraan)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NamaKendaraan)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoPolisi)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoPolisi)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoStnk)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoStnk)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ketersediaan)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ketersediaan)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdJenisKendaraanNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdJenisKendaraanNavigation.IdJenisKendaraan)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdKendaraan" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Kendaraans/Details.cshtml
@model RentalKendaraan_116.Models.Kendaraan

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Kendaraan</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NamaKendaraan)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NamaKendaraan)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoPolisi)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoPolisi)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoStnk)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoStnk)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ketersediaan)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ketersediaan)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdJenisKendaraanNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdJenisKendaraanNavigation.IdJenisKendaraan)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.IdKendaraan">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Kendaraans/Edit.cshtml
@model RentalKendaraan_116.Models.Kendaraan

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Kendaraan</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdKendaraan" />
            <div class="form-group">
                <label asp-for="NamaKendaraan" class="control-label"></label>
                <input asp-for="NamaKendaraan" class="form-control" />
                <span asp-validation-for="NamaKendaraan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoPolisi" class="control-label"></label>
                <input asp-for="NoPolisi" class="form-control" />
                <span asp-validation-for="NoPolisi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NoStnk" class="control-label"></label>
                <input asp-for="NoStnk" class="form-control" />
                <span asp-validation-for="NoStnk" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdJenisKendaraan" class="control-label"></label>
                <select asp-for="IdJenisKendaraan" class="form-control" asp-items="ViewBag.IdJenisKendaraan"></select>
                <span asp-validation-for="IdJenisKendaraan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ketersediaan" class="control-label"></label>
                <input asp-for="Ketersediaan" class="form-control" />
                <span asp-validation-for="Ketersediaan" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Kendaraans/Index.cshtml
@model IEnumerable<RentalKendaraan_116.Models.Kendaraan>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

@using (Html.BeginForm("Index", "Kendaraans", FormMethod.Get))
{
    <p>
        Ketersediaan: @Html.DropDownList("ktsd", "Pilih Ketersediaan")
        Cari Data : @Html.TextBox("searchString")
        <input type="submit" value="Filter" />
    </p>
}


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NamaKendaraan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoPolisi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NoStnk)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ketersediaan)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdJenisKendaraanNavigation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NamaKendaraan)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NoPolisi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NoStnk)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ketersediaan)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdJenisKendaraanNavigation.IdJenisKendaraan)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.IdKendaraan">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.IdKendaraan">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.IdKendaraan">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>